name = "jaffamonkey"
license = "MIT"
licenselink = "https://github.com/cncf/dot-org-hugo-theme/blob/main/LICENSE"
description = "TQuality engineering in the pipeline"
homepage = "https://bespoke-salamander-78886a.netlify.app"
demosite = "https://bespoke-salamander-78886a.netlify.app"
min_version = "0.110.0"
theme_version = "0.1.3"

tags = [
  "accessibility",
  "accessible",
  "archive",
  "blog",
  "clean",
  "company",
  "light",
  "modern",
  "multilingual",
  "performance",
  "project",
  "responsive",
  "simple",
  "white",
]

features = [
  "accessible",
  "blog",
  "buttons",
  "card",
  "columns",
  "custom-css",
  "custom-js",
  "faq",
  "favicon",
  "iframe",
  "mega-menu",
  "minified-assets",
  "mobile-menu",
  "multilingual",
  "responsive",
  "shortcodes",
  "single-column",
  "social-icons",
  "table-of-contents",
  "youtube",
]

[author]
  name = "jaffamonkey"
  homepage = "https://www.jaffamonkey.com/"
