en:
  languageName: English
  weight: 1
  ### copyright (markdown can be used) ###
  copyright: "Copyright &copy; {{< current_year >}} jaffamonkey ltd."
  title: "Quality engineering"
  description: "Quality engineering"
  params:
    ### accessibility ###
    accessibility:
      skip_text: "Skip to content"
      help_text: "Accessibility Statement"
      help_url: "/accessibilitystatement/"
    ### calls to action ###
    main_cta:
      text: "Book an intro meeting"
      link: "https://calendly.com/jaffamonkeyltd/intro-call"
    footer_cta:
      text: "Book an intro meeting"
      link: "https://calendly.com/jaffamonkeyltd/intro-call"
    github_edit: "Edit this page on GitHub"
  ### example menu showing children ###
  menu:
    main:
    - identifier: "about"
      name: "About"
      url: "/about/"
      weight: 1
    - identifier: "testing"
      name: "Testing"
      url: "/qualityengineering/"
      weight: 2
    - identifier: "quality-engineering"
      name: "Testing in the pipline"
      url: "/testinginci/"
      weight: 1
      post: "Lorem ipsum dolor sit amet consectetuer adipiscing elit aenean commodo."
      parent: "testing"
    # - identifier: "test-strategy"
    #   name: "Test Strategy"
    #   url: "/qualityengineering/"
    #   weight: 2
    #   post: "Nulla consequat massa quis enim. Donec pede justo."
    #   parent: "testing"
    # - identifier: "process-improvement"
    #   name: "Process improvement"
    #   url: "/processimprovement/"
    #   weight: 3
    #   post: "Aenean commodo ligula get dolor. Aenean massa. "
    #   parent: "testing"
    - identifier: "accessibility"
      name: "Accessibility"
      url: "/accessibilityaudit/"
      weight: 3
    - identifier: "accessibility-audit"
      name: "Accessibility audit"
      url: "/accessibilityaudit/"
      weight: 1
      post: "Accessibility audit."
      parent: "accessibility"
    - identifier: "faq"
      name: "FAQs"
      url: "/faq/"
      weight: 4
    # - identifier: "blog"
    #   name: "Blog"
    #   url: "/blog/"
    #   weight: 5
es:
  languageName: Spanish
  contentDir: content/es
  weight: 2
  title: "Título del Sitio"
  description: "Descripción del Sitio"
  menu:
    main:
    - identifier: "about"
      name: "Acerca de"
      url: "/accessibilityaudit/"
      weight: 1
    - identifier: "child-1"
      name: "Página Hija de Ejemplo"
      url: "/accessibilityaudit/"
      weight: 1
      parent: "about"
    - identifier: "faq"
      name: "FAQs"
      url: "/faq/"
      weight: 3
    - identifier: "blog"
      name: "Blog"
      url: "/blog/"
      weight: 2
